name: Cypress test run on pipeline  

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Cypress Run
        id: cypress
        uses: cypress-io/github-action@v4
        with:
          browser: chrome